from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 520, 81, 21))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 801, 491))
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 520, 81, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuLa_super_appli = QtGui.QMenu(self.menubar)
        self.menuLa_super_appli.setObjectName("menuLa_super_appli")
        self.menuSauvegarder = QtGui.QMenu(self.menuLa_super_appli)
        self.menuSauvegarder.setObjectName("menuSauvegarder")
        self.menuOutil = QtGui.QMenu(self.menubar)
        self.menuOutil.setObjectName("menuOutil")
        self.menuAMDE = QtGui.QMenu(self.menuOutil)
        self.menuAMDE.setObjectName("menuAMDE")
        self.menuSimulation = QtGui.QMenu(self.menuOutil)
        self.menuSimulation.setObjectName("menuSimulation")
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionExport2 = QtGui.QAction(MainWindow)
        self.actionExport2.setObjectName("actionExport2")
        self.actionPdf = QtGui.QAction(MainWindow)
        self.actionPdf.setObjectName("actionPdf")
        self.actionScenario = QtGui.QAction(MainWindow)
        self.actionScenario.setObjectName("actionScenario")
        self.actionAppli = QtGui.QAction(MainWindow)
        self.actionAppli.setObjectName("actionAppli")
        self.actionHtml = QtGui.QAction(MainWindow)
        self.actionHtml.setObjectName("actionHtml")
        self.actionGraph = QtGui.QAction(MainWindow)
        self.actionGraph.setObjectName("actionGraph")
        self.actionVisualisation = QtGui.QAction(MainWindow)
        self.actionVisualisation.setObjectName("actionVisualisation")
        self.actionModification = QtGui.QAction(MainWindow)
        self.actionModification.setObjectName("actionModification")
        self.actionChercher_cause = QtGui.QAction(MainWindow)
        self.actionChercher_cause.setObjectName("actionChercher_cause")
        self.actionStatistique = QtGui.QAction(MainWindow)
        self.actionStatistique.setObjectName("actionStatistique")
        self.actionHistogramme = QtGui.QAction(MainWindow)
        self.actionHistogramme.setObjectName("actionHistogramme")
        self.actionEffet = QtGui.QAction(MainWindow)
        self.actionEffet.setObjectName("actionEffet")
        self.actionCause = QtGui.QAction(MainWindow)
        self.actionCause.setObjectName("actionCause")
        self.menuSauvegarder.addAction(self.actionPdf)
        self.menuSauvegarder.addAction(self.actionHtml)
        self.menuLa_super_appli.addAction(self.menuSauvegarder.menuAction())
        self.menuLa_super_appli.addAction(self.actionExport)
        self.menuLa_super_appli.addAction(self.actionExport2)
        self.menuAMDE.addAction(self.actionVisualisation)
        self.menuAMDE.addAction(self.actionModification)
        self.menuSimulation.addAction(self.actionEffet)
        self.menuSimulation.addAction(self.actionCause)
        self.menuOutil.addAction(self.menuSimulation.menuAction())
        self.menuOutil.addAction(self.actionScenario)
        self.menuOutil.addAction(self.menuAMDE.menuAction())
        self.menuOutil.addAction(self.actionStatistique)
        self.menuOutil.addAction(self.actionHistogramme)
        self.menuOutil.addAction(self.actionGraph)
        self.menuAide.addAction(self.actionAppli)
        self.menubar.addAction(self.menuLa_super_appli.menuAction())
        self.menubar.addAction(self.menuOutil.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Outil AMDE", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLa_super_appli.setTitle(QtGui.QApplication.translate("MainWindow", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSauvegarder.setTitle(QtGui.QApplication.translate("MainWindow", "Sauvegarder", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOutil.setTitle(QtGui.QApplication.translate("MainWindow", "Outils", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAMDE.setTitle(QtGui.QApplication.translate("MainWindow", "AMDE", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setTitle(QtGui.QApplication.translate("MainWindow", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAide.setTitle(QtGui.QApplication.translate("MainWindow", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "Export Stat", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport2.setText(QtGui.QApplication.translate("MainWindow", "Export Relation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPdf.setText(QtGui.QApplication.translate("MainWindow", "PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScenario.setText(QtGui.QApplication.translate("MainWindow", "Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAppli.setText(QtGui.QApplication.translate("MainWindow", "Appli", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHtml.setText(QtGui.QApplication.translate("MainWindow", "HTML", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVisualisation.setText(QtGui.QApplication.translate("MainWindow", "Visualisation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModification.setText(QtGui.QApplication.translate("MainWindow", "Modification", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChercher_cause.setText(QtGui.QApplication.translate("MainWindow", "Chercher cause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStatistique.setText(QtGui.QApplication.translate("MainWindow", "Statistique", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHistogramme.setText(QtGui.QApplication.translate("MainWindow", "Histogramme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGraph.setText(QtGui.QApplication.translate("MainWindow", "Graphe", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEffet.setText(QtGui.QApplication.translate("MainWindow", "Effet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCause.setText(QtGui.QApplication.translate("MainWindow", "Cause", None, QtGui.QApplication.UnicodeUTF8))

